# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Pull-Request-or-Main

on:
  push:
    branches:
      - main

env:
  DEFAULT_TARGET_PLATFORM: 'Eclipse-2024-03'

jobs:
  platform:
    strategy:
      fail-fast: false
      matrix:
        target-platform: ['Eclipse-2024-03']
        distribution: [ temurin ]
        java-version: [ 17 ]
        maven-version: [ 3.9 ]
        os: [ ubuntu-22.04 ]
    runs-on: ${{ matrix.os }}
    container:
      image: maven:${{ matrix.maven-version }}
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: '${{ matrix.java-version }}'
        distribution: '${{ matrix.distribution }}'
        cache: maven
    - name: 'Build for platform: ${{ matrix.target-platform }}'
      run: 'mvn -ntp -Dtarget.platform=${{ matrix.target-platform }} -Dsite.dir=testing clean verify'
