# This workflow will create a Pull Request when a new branch is created in github

name: Create PR for a new branch

on:
  create:
    branches: [ "**" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
    - uses: actions/checkout@v4.1.1
    - run: gh pr list
      env:
        GH_TOKEN: ${{ github.token }}
    - run: echo "${{ github.ref_name }}"
    - run: echo "${{ github.repository }}"
    - name: Create Pull Request
      run: gh pr create -B main --title "PR for ${{ github.ref_name }} to main" --body "Auto created by GitHub action" -R "${{ github.repository }}"
      env:
        GH_TOKEN: ${{ github.token }}